### ISSUE TITLE
New onboarding process for DAP registration

### ISSUE THREAD

**Issue by MaroyaF** [18F/analytics.usa.gov#1257]
- [x] Create registration form on Touchpoints
- [x] Schedule meeting with VA to discuss new process
- [x] Instruct POC's to register for Touchpoints
```[tasklist]
### Tasks
```
