### ISSUE TITLE
As a user, I want up-to-date API documentation

### ISSUE THREAD

**Issue by tdlowden** [18F/analytics.usa.gov#544]
## What kind of issue?
- [x] Feature Request?
- [ ] Bug

## User story
*Please provide us with a description of the issue as a user story*
As an API user, I want to make sure I have up-to-date information on features and protocol for using the API.

## Acceptance Criteria
- [ ] As an API consumer, I want to know that I need to update my calls to reflect the correct version.

## Tasks (Optional)

- [ ] Update versioning documentation
- [ ] Add infor for the new filtering capabilities

**Comment by tdlowden** [comment]
completed.
